name: TTTMedicine
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  flutter_slidable: ^3.1.1
  flutter_advanced_switch: ^3.1.0
  intl: ^0.18.0
#  persistent_bottom_nav_bar: ^5.0.2
  group_button: ^5.3.4
  time_pickerr: ^1.0.6

  # firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1

  # GetX
  get: ^4.6.6
  get_storage: ^2.1.1
  path_provider: ^2.1.4

  # NoSql
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  provider:
  timestamp_to_string: ^0.0.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0

  # Network
  http: ^0.13.3
  http_interceptor: ^1.0.2
  dartz: ^0.10.1
  logger: ^1.1.0
  cached_network_image: ^3.3.1

  # common
  lottie: ^2.7.0
  shake: ^2.2.0
  flutter_parsed_text: ^2.2.1

  # speech
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

  # file
  image_picker: ^1.1.1

  # alarm clock
#  android_alarm_manager_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/flags/
    - assets/lotties/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf